#!/bin/bash
# Quick Terminal Commands for GitHub Setup

echo "=== ImageShield GitHub Setup ==="
echo ""
echo "STEP 1: Initialize Git Repository"
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit: ImageShield image protection tool'"
echo ""
echo "STEP 2: Connect to GitHub Remote"
echo "git remote add origin https://github.com/YOUR_USERNAME/ImageShield.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "STEP 3: Verify Upload (check GitHub.com)"
echo ""
echo "STEP 4: Build and Release DMG for Users"
echo "./scripts/build_macos.sh"
echo ""
echo "STEP 5: Create GitHub Release (option A - using GitHub CLI)"
echo "brew install gh  # if needed"
echo "gh release create v1.0.0 ./dist/dmg/ImageShield.dmg --title 'ImageShield v1.0.0'"
echo ""
echo "STEP 5 (option B - manual via GitHub.com)"
echo "1. Go to: https://github.com/YOUR_USERNAME/ImageShield/releases"
echo "2. Click 'Draft a new release'"
echo "3. Tag: v1.0.0"
echo "4. Upload: dist/dmg/ImageShield.dmg"
echo "5. Publish"
echo ""
echo "=== Done! ==="
echo "Users download DMG from Releases"
echo "Teammates clone repo and run: python app.py"
